export { default as AboutSection } from './AboutSection'
export { default as HeroSection } from './HeroSection'
export { default as DexSection } from './DexSection'
export { default as BuySection } from './BuySection'
export { default as FaqSection } from './FaqSection'
